<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>run.endive</groupId>
    <artifactId>endive</artifactId>
    <version>999-SNAPSHOT</version>
  </parent>
  <artifactId>wasm-tools</artifactId>
  <packaging>jar</packaging>

  <name>Endive - wasm-tools</name>
  <description>wasm tools compiled to pure Java with Endive</description>

  <properties>
    <wasm-tools.version>1.256.0</wasm-tools.version>
    <inlay.version>0.0.3</inlay.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>io.roastedroot</groupId>
      <artifactId>zerofs</artifactId>
    </dependency>
    <dependency>
      <groupId>run.endive</groupId>
      <artifactId>log</artifactId>
    </dependency>
    <dependency>
      <groupId>run.endive</groupId>
      <artifactId>runtime</artifactId>
    </dependency>
    <dependency>
      <groupId>run.endive</groupId>
      <artifactId>wasi</artifactId>
    </dependency>
    <dependency>
      <groupId>run.endive</groupId>
      <artifactId>wasm</artifactId>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-api</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>io.roastedroot</groupId>
        <artifactId>inlay-maven-plugin</artifactId>
        <version>${inlay.version}</version>
        <executions>
          <execution>
            <id>fetch-wasm-tools</id>
            <goals>
              <goal>fetch</goal>
            </goals>
            <configuration>
              <modules>
                <module>
                  <imageRef>ghcr.io/bytecodealliance/wasm-tools-wasm32-wasip1:${wasm-tools.version}</imageRef>
                  <outputFile>${project.build.directory}/wasm-tools.wasm</outputFile>
                </module>
              </modules>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>run.endive</groupId>
        <artifactId>endive-compiler-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>wasmtools</id>
            <goals>
              <goal>compile</goal>
            </goals>
            <configuration>
              <name>run.endive.tools.wasm.WasmToolsModule</name>
              <wasmFile>${project.build.directory}/wasm-tools.wasm</wasmFile>
              <!-- <interpreterFallback>WARN</interpreterFallback> -->
              <interpretedFunctions>
                <function>5197</function>
                <function>5521</function>
                <function>6096</function>
              </interpretedFunctions>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
