package run.endive.testgen;

import java.io.IOException;
import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Random;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/** Generates the committed v128 corpus using Wasmtime as the oracle. */
public final class V128CorpusGenerator {
    private static final long SEED = 0x5EEDL;
    private static final BigInteger TWO_TO_128 = BigInteger.ONE.shiftLeft(128);
    private static final Pattern OPCODE_PATTERN =
            Pattern.compile("^\\s+([A-Za-z0-9_]+)\\(0x(FD[0-9A-F]+)");
    private static final String[] LANE_KEYS =
            "I8x16,I16x8,I32x4,F32x4,I64x2,F64x2,8_LANE,16_LANE,32_LANE,64_LANE".split(",");
    private static final int[] LANE_COUNTS = {16, 8, 4, 4, 2, 2, 16, 8, 4, 2};
    private static final String[] VECTOR_TYPES = {"i8x16", "i16x8", "i32x4", "i64x2"};

    private V128CorpusGenerator() {}

    public static void main(String[] args) throws Exception {
        if (args.length != 3) {
            throw new IllegalArgumentException(
                    "usage: V128CorpusGenerator <wasmtime-binary> <OpCode.java> <output.wast>");
        }
        Path wasmtime = Path.of(args[0]);
        List<String> opcodes = new ArrayList<>();
        for (String line : Files.readAllLines(Path.of(args[1]), StandardCharsets.UTF_8)) {
            Matcher matcher = OPCODE_PATTERN.matcher(line);
            if (matcher.find()) {
                opcodes.add(matcher.group(1));
            }
        }
        if (opcodes.size() != 236) {
            throw new IllegalStateException("expected 236 v128 opcodes, found " + opcodes.size());
        }
        List<Case> cases = makeCases(opcodes);
        Path output = Path.of(args[2]);
        String module = moduleText(cases);
        Path wat = Files.createTempFile("endive-v128-", ".wat");
        try {
            Files.writeString(wat, module, StandardCharsets.UTF_8);
            StringBuilder text =
                    new StringBuilder(
                                    String.format(
                                            Locale.ROOT,
                                            ";; Generated by GenerateV128Corpus.java.\n"
                                                + ";; Seed: 0x5eed; opcodes: %d; cases: %d.\n"
                                                + ";; Expectations were computed by the Wasmtime"
                                                + " executable supplied to the generator.\n",
                                            opcodes.size(),
                                            cases.size()))
                            .append(module)
                            .append('\n');
            for (Case testCase : cases) {
                if (testCase.trap) {
                    text.append(
                            String.format(
                                    Locale.ROOT,
                                    "(assert_trap (invoke \"%s\") \"out of bounds memory"
                                            + " access\")\n",
                                    testCase.export));
                } else {
                    text.append("(assert_return (invoke \"")
                            .append(testCase.export)
                            .append("\") ")
                            .append(expected(testCase, invoke(wasmtime, wat, testCase)))
                            .append(")\n");
                }
            }
            if (output.getParent() != null) {
                Files.createDirectories(output.getParent());
            }
            Files.writeString(output, text.toString(), StandardCharsets.UTF_8);
            System.out.printf(
                    Locale.ROOT,
                    "generated %s (%d opcodes, %d cases)%n",
                    output,
                    opcodes.size(),
                    cases.size());
        } finally {
            Files.deleteIfExists(wat);
        }
    }

    private static int laneCount(String opcode) {
        for (int i = 0; i < LANE_KEYS.length; i++) {
            if (opcode.contains(LANE_KEYS[i])) {
                return LANE_COUNTS[i];
            }
        }
        throw new IllegalStateException("cannot determine lane count for " + opcode);
    }

    private static String scalarType(String opcode) {
        return opcode.matches(".*(ANY_TRUE|ALL_TRUE|BITMASK)$")
                ? "i32"
                : opcode.contains("F32x4")
                        ? "f32"
                        : opcode.contains("F64x2")
                                ? "f64"
                                : opcode.contains("I64x2") ? "i64" : "i32";
    }

    private static boolean isMemory(String opcode) {
        return opcode.startsWith("V128_LOAD") || opcode.startsWith("V128_STORE");
    }

    private static boolean isStore(String opcode) {
        return opcode.startsWith("V128_STORE");
    }

    private static boolean isLane(String opcode) {
        return opcode.contains("LANE") && !opcode.equals("I8x16_SHUFFLE");
    }

    private static String vectorLaneType(String opcode) {
        boolean f32 = opcode.startsWith("F32x4_");
        boolean f64 = opcode.startsWith("F64x2_");
        if ((f32 || f64) && opcode.matches(".*_(EQ|NE|LT|GT|LE|GE)$")) {
            return f32 ? "i32x4" : "i64x2";
        }
        if (f32) {
            return "f32x4";
        }
        if (f64) {
            return "f64x2";
        }
        if (opcode.startsWith("V128_LOAD8x8") || opcode.equals("V128_LOAD16_SPLAT")) {
            return "i16x8";
        }
        if (opcode.startsWith("V128_LOAD16x4")) {
            return "i32x4";
        }
        if (opcode.startsWith("V128_LOAD32x2") || opcode.equals("V128_LOAD64_ZERO")) {
            return "i64x2";
        }
        if (opcode.startsWith("V128_LOAD32_")) {
            return "i32x4";
        }
        if (opcode.startsWith("I64x2_")) {
            return "i64x2";
        }
        for (int i = 0; i < VECTOR_TYPES.length; i++) {
            if (opcode.startsWith(LANE_KEYS[i] + "_") || opcode.contains(LANE_KEYS[i + 6])) {
                return VECTOR_TYPES[i];
            }
        }
        return "i8x16";
    }

    private static byte[] vectorBytes(Random random, boolean edge, int floatExtract) {
        if (floatExtract == 32) {
            double[] values =
                    edge ? new double[] {0.0, -1.0, 1.5, 42.25} : randomDoubles(random, 4);
            byte[] result = new byte[16];
            for (int i = 0; i < values.length; i++) {
                putLE(result, i * 4, Float.floatToRawIntBits((float) values[i]), 4);
            }
            return result;
        }
        if (floatExtract == 64) {
            double[] values = edge ? new double[] {0.0, -1.0} : randomDoubles(random, 2);
            byte[] result = new byte[16];
            for (int i = 0; i < values.length; i++) {
                putLE(result, i * 8, Double.doubleToRawLongBits(values[i]), 8);
            }
            return result;
        }
        if (edge) {
            byte[][] choices = {
                packed(1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
                fill((byte) 0xFF),
                packed(1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15),
                fill((byte) 0x80),
                packed(4, 0x80000000, 0x7FFFFFFF, 1, 0xFFFFFFFF),
                packed(8, 0x8000000000000000L, 0x7FFFFFFFFFFFFFFFL)
            };
            return choices[random.nextInt(choices.length)];
        }
        byte[] result = new byte[16];
        for (int i = 0; i < result.length; i++) {
            result[i] = (byte) random.nextInt(256);
        }
        return result;
    }

    private static double[] randomDoubles(Random random, int count) {
        return java.util.stream.DoubleStream.generate(() -> -1000.0 + 2000.0 * random.nextDouble())
                .limit(count)
                .toArray();
    }

    private static byte[] fill(byte value) {
        byte[] result = new byte[16];
        java.util.Arrays.fill(result, value);
        return result;
    }

    private static byte[] packed(int width, long... values) {
        byte[] result = new byte[values.length * width];
        for (int i = 0; i < values.length; i++) {
            putLE(result, i * width, values[i], width);
        }
        return result;
    }

    private static void putLE(byte[] target, int offset, long value, int width) {
        for (int i = 0; i < width; i++) {
            target[offset + i] = (byte) (value >>> (i * 8));
        }
    }

    private static String vconst(byte[] value) {
        java.util.StringJoiner lanes = new java.util.StringJoiner(" ");
        for (byte item : value) {
            lanes.add(Byte.toString(item));
        }
        return "(v128.const i8x16 " + lanes + ")";
    }

    private static String scalarLiteral(String kind, Number value) {
        if (kind.equals("i32") || kind.equals("i64")) {
            return "(" + kind + ".const " + value.longValue() + ")";
        }
        int width = kind.equals("f32") ? 32 : 64;
        long bits =
                kind.equals("f32")
                        ? Integer.toUnsignedLong(Float.floatToRawIntBits(value.floatValue()))
                        : Double.doubleToRawLongBits(value.doubleValue());
        return "(" + kind + ".const " + floatLiteral(bits, width, null) + ")";
    }

    private static String floatLiteral(long bits, int width, String pattern) {
        int fractionBits = width == 32 ? 23 : 52;
        int exponentBits = width == 32 ? 8 : 11;
        long fractionMask = (1L << fractionBits) - 1;
        long fraction = bits & fractionMask;
        long exponent = (bits >>> fractionBits) & ((1L << exponentBits) - 1);
        boolean negative = (bits >>> (width - 1) & 1) != 0;
        String sign = negative ? "-" : "";
        long maximumExponent = (1L << exponentBits) - 1;
        if (exponent == maximumExponent && fraction != 0) {
            return pattern != null ? pattern : sign + "nan:0x" + Long.toHexString(fraction);
        }
        if (exponent == maximumExponent) {
            return sign + "inf";
        }
        if (exponent == 0 && fraction == 0) {
            return sign + "0x0.0p+0";
        }
        int exponentBase = width == 32 ? 127 : 1023;
        int highestBit = 63 - Long.numberOfLeadingZeros(fraction);
        int unbiasedExponent =
                exponent == 0
                        ? highestBit + 1 - exponentBase - fractionBits
                        : (int) exponent - exponentBase;
        long normalizedFraction =
                exponent == 0
                        ? (fraction - (1L << highestBit)) << (52 - highestBit)
                        : fraction << (52 - fractionBits);
        return String.format(
                Locale.ROOT,
                "%s0x1.%013xp%s%d",
                sign,
                normalizedFraction,
                unbiasedExponent >= 0 ? "+" : "",
                unbiasedExponent);
    }

    private static String expression(
            String opcode, List<byte[]> vectors, List<Number> scalars, int lane, int address) {
        if (vectors.isEmpty()
                && !isMemory(opcode)
                && !opcode.equals("V128_CONST")
                && !opcode.contains("SPLAT")) {
            throw new IllegalStateException("expression missing vector for " + opcode);
        }
        int underscore = opcode.indexOf('_');
        String op =
                opcode.substring(0, underscore).toLowerCase(Locale.ROOT)
                        + "."
                        + opcode.substring(underscore + 1).toLowerCase(Locale.ROOT);
        if (op.equals("f32x4.demote_low_f64x2_zero")) {
            op = "f32x4.demote_f64x2_zero";
        }
        if (isMemory(opcode)) {
            String addr = "(i32.const " + address + ")";
            if (isLane(opcode)) {
                return call(op, "offset=0", "align=1", lane, addr, vconst(vectors.get(0)));
            }
            if (isStore(opcode)) {
                return call(op, "offset=0", "align=1", addr, vconst(vectors.get(0)));
            }
            return call(op, "offset=0", "align=1", addr);
        }
        if (opcode.equals("V128_CONST")) {
            return vconst(vectors.get(0));
        }
        if (opcode.equals("I8x16_SHUFFLE")) {
            java.util.StringJoiner lanes = new java.util.StringJoiner(" ");
            for (int i = 0; i < 16; i++) {
                lanes.add(Integer.toString((lane + i) % 32));
            }
            return call(op, lanes, vconst(vectors.get(0)), vconst(vectors.get(1)));
        }
        if (isLane(opcode)) {
            String args = lane + " " + vconst(vectors.get(0));
            if (opcode.contains("REPLACE_LANE")) {
                args += " " + scalarLiteral(scalarType(opcode), scalars.get(0));
            }
            return "(" + op + " " + args + ")";
        }
        if (opcode.contains("SPLAT")) {
            return call(op, scalarLiteral(scalarType(opcode), scalars.get(0)));
        }
        if (opcode.contains("SHL") || opcode.contains("SHR")) {
            return call(op, vconst(vectors.get(0)), scalarLiteral("i32", scalars.get(0)));
        }
        if (opcode.equals("I8x16_SWIZZLE")) {
            return call(op, vconst(vectors.get(0)), vconst(vectors.get(1)));
        }
        if (opcode.equals("V128_BITSELECT")) {
            return call(op, vconst(vectors.get(0)), vconst(vectors.get(1)), vconst(vectors.get(2)));
        }
        if (isUnary(opcode) || opcode.matches(".*(ANY_TRUE|ALL_TRUE|BITMASK)$")) {
            return call(op, vconst(vectors.get(0)));
        }
        return call(op, vconst(vectors.get(0)), vconst(vectors.get(1)));
    }

    private static String call(String op, Object... args) {
        java.util.StringJoiner result = new java.util.StringJoiner(" ", "(" + op + " ", ")");
        for (Object arg : args) {
            result.add(String.valueOf(arg));
        }
        return result.toString();
    }

    private static boolean isUnary(String opcode) {
        return opcode.matches(
                ".*(V128_NOT|ABS|NEG|POPCNT|SQRT|CEIL|FLOOR|TRUNC|EXTEND|EXTADD|NEAREST|CONVERT|PROMOTE|DEMOTE).*");
    }

    private static List<Case> makeCases(List<String> opcodes) {
        List<Case> cases = new ArrayList<>();
        for (int index = 0; index < opcodes.size(); index++) {
            String opcode = opcodes.get(index);
            boolean vector =
                    !(opcode.contains("EXTRACT_LANE")
                            || opcode.matches(".*(ANY_TRUE|ALL_TRUE|BITMASK)$"));
            String laneType = vectorLaneType(opcode);
            String resultType = vector ? null : scalarType(opcode);
            for (int variant = 0; variant < 2; variant++) {
                boolean edge = variant == 0;
                Random random = new Random(SEED + index * 0x9E3779B1L + (edge ? 0 : 1));
                int vectorsNeeded;
                if (opcode.equals("V128_CONST")) {
                    vectorsNeeded = 1;
                } else if (isMemory(opcode)) {
                    vectorsNeeded = isStore(opcode) || isLane(opcode) ? 1 : 0;
                } else if (isUnary(opcode)
                        || opcode.contains("SPLAT")
                        || opcode.contains("EXTRACT_LANE")
                        || opcode.contains("REPLACE_LANE")
                        || opcode.matches(".*(ANY_TRUE|ALL_TRUE|BITMASK)$")) {
                    vectorsNeeded =
                            opcode.contains("EXTRACT_LANE") || opcode.contains("REPLACE_LANE")
                                    ? 1
                                    : 0;
                } else {
                    vectorsNeeded = opcode.equals("V128_BITSELECT") ? 3 : 2;
                }
                List<byte[]> vectors = new ArrayList<>();
                int floatExtract =
                        opcode.contains("F32x4") && opcode.contains("EXTRACT_LANE")
                                ? 32
                                : opcode.contains("F64x2") && opcode.contains("EXTRACT_LANE")
                                        ? 64
                                        : 0;
                for (int i = 0; i < vectorsNeeded; i++) {
                    vectors.add(vectorBytes(random, edge, floatExtract));
                }
                List<Number> scalars = new ArrayList<>();
                if (opcode.contains("SPLAT") || opcode.contains("REPLACE_LANE")) {
                    String kind = scalarType(opcode);
                    if (kind.equals("i32")) {
                        long[] values = {0, -1, 1, Integer.MIN_VALUE, Integer.MAX_VALUE};
                        scalars.add(edge ? values[index % values.length] : random.nextInt());
                    } else if (kind.equals("i64")) {
                        long[] values = {0, -1, 1, Long.MIN_VALUE, Long.MAX_VALUE};
                        scalars.add(edge ? values[index % values.length] : random.nextLong());
                    } else {
                        double[] values = {0.0, -1.0, 1.0, 42.25};
                        scalars.add(
                                edge
                                        ? values[index % values.length]
                                        : -1000.0 + 2000.0 * random.nextDouble());
                    }
                }
                if (opcode.endsWith("ANY_TRUE")
                        || opcode.endsWith("ALL_TRUE")
                        || opcode.endsWith("BITMASK")) {
                    vectors = new ArrayList<>();
                    vectors.add(vectorBytes(random, edge, 0));
                }
                if (opcode.contains("SHL") || opcode.contains("SHR")) {
                    scalars = new ArrayList<>();
                    scalars.add(edge ? index % 8 : random.nextInt(256));
                }
                boolean laneSensitive =
                        isLane(opcode)
                                || opcode.contains("EXTRACT_LANE")
                                || opcode.contains("REPLACE_LANE");
                int lane =
                        laneSensitive
                                ? (edge
                                        ? index % laneCount(opcode)
                                        : random.nextInt(laneCount(opcode)))
                                : index % 16;
                if (isUnary(opcode)) {
                    vectors = new ArrayList<>();
                    vectors.add(vectorBytes(random, edge, 0));
                }
                if (vectors.isEmpty()
                        && !isMemory(opcode)
                        && !opcode.equals("V128_CONST")
                        && !opcode.contains("SPLAT")
                        && !isUnary(opcode)
                        && !opcode.endsWith("ANY_TRUE")
                        && !opcode.endsWith("ALL_TRUE")
                        && !opcode.endsWith("BITMASK")) {
                    throw new IllegalStateException("no vector inputs for " + opcode);
                }
                String name = opcode.toLowerCase(Locale.ROOT) + (edge ? "_edge" : "_random");
                cases.add(
                        new Case(
                                opcode,
                                name,
                                expression(opcode, vectors, scalars, lane, 16),
                                vector,
                                laneType,
                                resultType,
                                (opcode.startsWith("F32x4_") || opcode.startsWith("F64x2_"))
                                        && (opcode.matches(
                                                        ".*_(ADD|SUB|MUL|DIV|SQRT|CEIL|FLOOR|TRUNC|NEAREST|CONVERT|PROMOTE|DEMOTE).*")
                                                || ((opcode.contains("_MIN")
                                                                || opcode.contains("_MAX"))
                                                        && !opcode.contains("_PMIN")
                                                        && !opcode.contains("_PMAX"))),
                                false));
            }
            if (opcode.startsWith("V128_LOAD") || opcode.startsWith("V128_STORE")) {
                Random random = new Random(SEED + index * 0x9E3779B1L + 2);
                List<byte[]> vectors = new ArrayList<>();
                if (isStore(opcode) || isLane(opcode)) {
                    vectors.add(vectorBytes(random, true, 0));
                }
                int lane = isLane(opcode) ? index % laneCount(opcode) : 0;
                int width =
                        opcode.equals("V128_LOAD") || opcode.equals("V128_STORE")
                                ? 16
                                : opcode.matches(".*(LOAD8x8|LOAD8_SPLAT|8_LANE).*")
                                        ? 1
                                        : opcode.matches(".*(LOAD16x4|LOAD16_SPLAT|16_LANE).*")
                                                ? 2
                                                : opcode.matches(
                                                                ".*(LOAD32x2|LOAD32_SPLAT|32_LANE|LOAD32_ZERO).*")
                                                        ? 4
                                                        : opcode.matches(
                                                                        ".*(LOAD64_SPLAT|64_LANE|LOAD64_ZERO).*")
                                                                ? 8
                                                                : 16;
                int address = 65536 - width + 1;
                cases.add(
                        new Case(
                                opcode,
                                opcode.toLowerCase(Locale.ROOT) + "_trap",
                                expression(opcode, vectors, new ArrayList<>(), lane, address),
                                true,
                                laneType,
                                null,
                                false,
                                true));
            }
        }
        return cases;
    }

    private static String moduleText(List<Case> cases) {
        StringBuilder module = new StringBuilder("(module\n  (memory 1)\n  (data \"");
        for (int i = 0; i < 64; i++) {
            module.append(String.format(Locale.ROOT, "\\%02x", (i * 73 + 19) & 0xFF));
        }
        module.append("\")\n");
        for (int i = 0; i < cases.size(); i++) {
            if (i != 0) {
                module.append('\n');
            }
            Case testCase = cases.get(i);
            module.append("  (func (export \"").append(testCase.export).append("\") (result ");
            if (!testCase.vector) {
                module.append(testCase.scalarType).append(")\n    ").append(testCase.expression);
            } else {
                module.append("v128) (local v128)\n");
                if (isMemory(testCase.opcode)) {
                    module.append(
                            "    (memory.init 0 (i32.const 0) (i32.const 0) (i32.const 64))\n");
                }
                module.append("    ").append(testCase.expression);
                if (isStore(testCase.opcode)) {
                    module.append("\n    (v128.load offset=0 align=1 (i32.const 16))");
                }
            }
            module.append("\n  )");
        }
        return module.append("\n)\n").toString();
    }

    private static List<String> invoke(Path wasmtime, Path wat, Case testCase) throws IOException {
        Process process =
                new ProcessBuilder(
                                wasmtime.toString(),
                                "run",
                                "--invoke",
                                testCase.export,
                                wat.toString())
                        .start();
        String stdout = new String(process.getInputStream().readAllBytes(), StandardCharsets.UTF_8);
        String stderr = new String(process.getErrorStream().readAllBytes(), StandardCharsets.UTF_8);
        try {
            if (process.waitFor() != 0) {
                throw new IllegalStateException(
                        "Wasmtime failed for " + testCase.export + ": " + stderr.trim());
            }
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            throw new IllegalStateException("Interrupted while invoking " + testCase.export, e);
        }
        return java.util.Arrays.stream(stdout.split("\\R"))
                .map(String::trim)
                .filter(line -> !line.isEmpty())
                .collect(java.util.stream.Collectors.toList());
    }

    private static String expected(Case testCase, List<String> output) {
        if (testCase.vector) {
            if (output.size() != 1) {
                throw new IllegalStateException(
                        "expected one v128 result for " + testCase.export + ", got " + output);
            }
            BigInteger value = new BigInteger(output.get(0)).mod(TWO_TO_128);
            byte[] raw = new byte[16];
            byte[] bytes = value.toByteArray();
            for (int i = 0; i < raw.length && i < bytes.length; i++) {
                raw[i] = bytes[bytes.length - i - 1];
            }
            int width =
                    Integer.parseInt(
                            testCase.laneType.substring(1, testCase.laneType.indexOf('x')));
            java.util.StringJoiner tokens = new java.util.StringJoiner(" ");
            for (int i = 0; i < 128 / width; i++) {
                long bits = 0;
                for (int j = 0; j < width / 8; j++) {
                    bits |= (long) (raw[i * width / 8 + j] & 0xFF) << (j * 8);
                }
                if (testCase.laneType.charAt(0) == 'f') {
                    boolean nan =
                            width == 32
                                    ? Float.isNaN(Float.intBitsToFloat((int) bits))
                                    : Double.isNaN(Double.longBitsToDouble(bits));
                    tokens.add(
                            floatLiteral(
                                    bits,
                                    width,
                                    testCase.arithmeticFloat && nan ? "nan:arithmetic" : null));
                } else {
                    long signed = bits;
                    if (width != 64) {
                        long mask = (1L << width) - 1;
                        signed &= mask;
                        if (signed >= (1L << (width - 1))) {
                            signed -= 1L << width;
                        }
                    }
                    tokens.add(Long.toString(signed));
                }
            }
            return "(v128.const " + testCase.laneType + " " + tokens + ")";
        }
        String value = output.get(0);
        if (testCase.scalarType.equals("i32") || testCase.scalarType.equals("i64")) {
            return "(" + testCase.scalarType + ".const " + new BigInteger(value) + ")";
        }
        double parsed =
                Double.parseDouble(
                        value.toLowerCase(Locale.ROOT)
                                .replace("inf", "Infinity")
                                .replace("nan", "NaN"));
        if (Double.isNaN(parsed)) {
            return call(testCase.scalarType + ".const", "nan:arithmetic");
        }
        if (Double.isInfinite(parsed)) {
            return call(testCase.scalarType + ".const", parsed < 0 ? "-inf" : "inf");
        }
        return call(
                testCase.scalarType + ".const",
                floatLiteral(Double.doubleToRawLongBits(parsed), 64, null));
    }

    private static final class Case {
        private final String opcode;
        private final String export;
        private final String expression;
        private final String laneType;
        private final String scalarType;
        private final boolean vector;
        private final boolean arithmeticFloat;
        private final boolean trap;

        private Case(Object... values) {
            this.opcode = (String) values[0];
            this.export = (String) values[1];
            this.expression = (String) values[2];
            this.vector = (boolean) values[3];
            this.laneType = (String) values[4];
            this.scalarType = (String) values[5];
            this.arithmeticFloat = (boolean) values[6];
            this.trap = (boolean) values[7];
        }
    }
}
