<?xml version="1.0" encoding="UTF-8"?>
<project>

  <modelVersion>4.0.0</modelVersion>
  <groupId>run.endive</groupId>
  <artifactId>redline-e2e-it</artifactId>
  <version>0.0-SNAPSHOT</version>
  <packaging>jar</packaging>

  <properties>
    <maven.compiler.release>25</maven.compiler.release>
  </properties>

  <dependencies>
    <dependency>
      <groupId>run.endive</groupId>
      <artifactId>redline-api-experimental</artifactId>
      <version>@project.version@</version>
    </dependency>
    <dependency>
      <groupId>run.endive</groupId>
      <artifactId>redline-runner-experimental</artifactId>
      <version>@project.version@</version>
    </dependency>
    <dependency>
      <groupId>run.endive</groupId>
      <artifactId>runtime</artifactId>
      <version>@project.version@</version>
    </dependency>

    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-api</artifactId>
      <version>@junit.version@</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-engine</artifactId>
      <version>@junit.version@</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>@maven-compiler-plugin.version@</version>
        <configuration>
          <release>${maven.compiler.release}</release>
        </configuration>
      </plugin>
      <plugin>
        <groupId>run.endive</groupId>
        <artifactId>endive-compiler-maven-plugin</artifactId>
        <version>@project.version@</version>
        <executions>
          <execution>
            <id>compile-i32</id>
            <goals>
              <goal>compile</goal>
            </goals>
            <configuration>
              <name>endive.test.AddModule</name>
              <wasmFile>src/test/resources/add.wat.wasm</wasmFile>
              <interpreterFallback>WARN</interpreterFallback>
              <redlineExperimental>true</redlineExperimental>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

</project>
