<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>run.endive</groupId>
    <artifactId>redline-parent-experimental</artifactId>
    <version>999-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>
  <artifactId>redline-build-time-compiler-experimental</artifactId>
  <packaging>jar</packaging>
  <name>Endive - Redline Build Time Compiler</name>
  <description>Build-time native code generation via Cranelift</description>

  <dependencies>
    <dependency>
      <groupId>com.github.javaparser</groupId>
      <artifactId>javaparser-core</artifactId>
    </dependency>
    <dependency>
      <groupId>run.endive</groupId>
      <artifactId>build-time-compiler</artifactId>
    </dependency>
    <dependency>
      <groupId>run.endive</groupId>
      <artifactId>redline-api-experimental</artifactId>
    </dependency>
    <dependency>
      <groupId>run.endive</groupId>
      <artifactId>redline-compiler-experimental</artifactId>
    </dependency>
    <dependency>
      <groupId>run.endive</groupId>
      <artifactId>wasm</artifactId>
    </dependency>
  </dependencies>
</project>
