<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>run.endive</groupId>
    <artifactId>redline-parent-experimental</artifactId>
    <version>1.1.0</version>
    <relativePath>../pom.xml</relativePath>
  </parent>
  <artifactId>redline-runner-jffi-experimental</artifactId>
  <packaging>jar</packaging>
  <name>Endive - Redline Runner JFFI</name>
  <description>Native code execution via JFFI (Java 11+)</description>

  <dependencies>
    <dependency>
      <groupId>com.github.jnr</groupId>
      <artifactId>jffi</artifactId>
    </dependency>
    <dependency>
      <groupId>run.endive</groupId>
      <artifactId>redline-api-experimental</artifactId>
    </dependency>
    <dependency>
      <groupId>run.endive</groupId>
      <artifactId>redline-bridge-experimental</artifactId>
    </dependency>
    <dependency>
      <groupId>run.endive</groupId>
      <artifactId>runtime</artifactId>
    </dependency>
    <dependency>
      <groupId>run.endive</groupId>
      <artifactId>wasm</artifactId>
    </dependency>
    <dependency>
      <groupId>com.github.jnr</groupId>
      <artifactId>jffi</artifactId>
      <classifier>native</classifier>
      <scope>runtime</scope>
    </dependency>
  </dependencies>
</project>
