(module
  ;; `catch_ref` and `catch_all_ref` send a non-nullable `(ref exn)` to the handler label.

  (tag $e (param i32))

  (func $throw (param $val i32)
    (throw $e (local.get $val))
  )

  (func (export "catch-ref-non-null") (param $val i32) (result i32)
    (block $h (result i32 (ref exn))
      (try_table (result i32) (catch_ref $e $h)
        (call $throw (local.get $val))
        (i32.const 0)
      )
      (return)
    )
    (drop)
  )

  (func (export "catch-all-ref-non-null") (param $val i32) (result i32)
    (block $h (result (ref exn))
      (try_table (catch_all_ref $h)
        (call $throw (local.get $val))
      )
      (return (i32.const 0))
    )
    (drop)
    (local.get $val)
  )

  ;; the caught `(ref exn)` is usable: store it in a nullable local and rethrow it
  (func (export "rethrow-non-null") (param $val i32) (result i32)
    (local $exn exnref)
    (block $h (result (ref exn))
      (try_table (catch_all_ref $h)
        (call $throw (local.get $val))
      )
      (return (i32.const 0))
    )
    (local.set $exn)
    (block $h2 (result i32 (ref exn))
      (try_table (result i32) (catch_ref $e $h2)
        (local.get $exn)
        (throw_ref)
      )
      (return)
    )
    (drop)
  )

  ;; the nullable spelling has to keep working, `(ref exn)` is a subtype of `exnref`
  (func (export "catch-ref-nullable") (param $val i32) (result i32)
    (block $h (result i32 exnref)
      (try_table (result i32) (catch_ref $e $h)
        (call $throw (local.get $val))
        (i32.const 0)
      )
      (return)
    )
    (drop)
  )
)
